<?php

namespace SmaatCoda\EncryptedFilesystem\FilesystemAdapters;

use GuzzleHttp\Psr7\Stream;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Config;
use RecursiveIteratorIterator;
use SmaatCoda\EncryptedFilesystem\EncryptionStreams\DecryptingStreamDecorator;
use SmaatCoda\EncryptedFilesystem\EncryptionStreams\EncryptingStreamDecorator;
use SmaatCoda\EncryptedFilesystem\Interfaces\CipherMethodInterface;
use SplFileInfo;

class EncryptedLocalAdapter extends Local
{
    /**
     * This extension is appended to encrypted files and will be checked for before decryption
     */
    const FILENAME_POSTFIX = '.enc';

    /**
     * @var CipherMethodInterface
     */
    protected $cipherMethod;

    /**
     * EncryptedFilesystemAdapter constructor.
     * @param CipherMethodInterface $cipherMethod
     * @param $root
     * @param int $writeFlags
     * @param int $linkHandling
     * @param array $permissions
     */
    public function __construct(CipherMethodInterface $cipherMethod, $root, $writeFlags = LOCK_EX, $linkHandling = self::DISALLOW_LINKS, array $permissions = [])
    {
        $this->cipherMethod = $cipherMethod;

        parent::__construct($root, $writeFlags, $linkHandling, $permissions);
    }

    public function has($path)
    {
        return parent::has($path) || parent::has($this->attachEncryptionMarkers($path));
    }

    public function write($path, $contents, Config $config)
    {
        $location = $this->attachEncryptionMarkers($this->applyPathPrefix($path));
        $this->ensureDirectory(dirname($location));

        $stream = new Stream(fopen("data://text/plain,$contents", 'rb'));
        $encryptedStream = new EncryptingStreamDecorator($stream, $this->cipherMethod);
        $outputStream = new Stream(fopen($location, 'wb'));

        while (!$encryptedStream->eof()) {
            $outputStream->write($encryptedStream->read($this->cipherMethod->getBlockSize()));
        }

        $type = 'file';
        $size = $encryptedStream->getSize();
        $result = compact('contents', 'type', 'size', 'path');

        if ($visibility = $config->get('visibility')) {
            $result['visibility'] = $visibility;
            $this->setVisibility($path, $visibility);
        }

        return $result;
    }

    public function writeStream($path, $resource, Config $config)
    {
        $location = $this->attachEncryptionMarkers($this->applyPathPrefix($path));
        $this->ensureDirectory(dirname($location));
        $stream = new Stream($resource);
        $encryptedStream = new EncryptingStreamDecorator($stream, $this->cipherMethod);
        $outputStream = new Stream(fopen($location, 'wb'));

        while (!$encryptedStream->eof()) {
            $outputStream->write($encryptedStream->read($this->cipherMethod->getBlockSize()));
        }

        $type = 'file';
        $result = compact('type', 'path');

        if ($visibility = $config->get('visibility')) {
            $this->setVisibility($path, $visibility);
            $result['visibility'] = $visibility;
        }

        return $result;
    }

    public function readStream($path)
    {
        $location = $this->attachEncryptionMarkers($this->applyPathPrefix($path));
        $stream = new Stream(fopen($location, 'rb'));
        $decryptedStream = new DecryptingStreamDecorator($stream, $this->cipherMethod);

        return ['type' => 'file', 'path' => $path, 'stream' => $decryptedStream];  // TODO: figure out if this works
    }

    public function update($path, $contents, Config $config)
    {
        return $this->write($path, $contents, $config);
    }

    public function read($path)
    {
        return parent::read($path); // TODO: Change the autogenerated stub
    }

    public function rename($path, $newpath)
    {
        return parent::rename($path, $newpath); // TODO: Change the autogenerated stub
    }

    public function copy($path, $newpath)
    {
        return parent::copy($path, $newpath); // TODO: Change the autogenerated stub
    }

    public function delete($path)
    {
        return parent::delete($path); // TODO: Change the autogenerated stub
    }

    public function listContents($directory = '', $recursive = false)
    {
        return parent::listContents($directory, $recursive); // TODO: Change the autogenerated stub
    }

    public function getMetadata($path)
    {
        return parent::getMetadata($path); // TODO: Change the autogenerated stub
    }

    public function getSize($path)
    {
        return parent::getSize($path); // TODO: Change the autogenerated stub
    }

    public function getMimetype($path)
    {
        return parent::getMimetype($path); // TODO: Change the autogenerated stub
    }

    public function getTimestamp($path)
    {
        return parent::getTimestamp($path); // TODO: Change the autogenerated stub
    }

    public function getVisibility($path)
    {
        return parent::getVisibility($path); // TODO: Change the autogenerated stub
    }

    public function setVisibility($path, $visibility)
    {
        return parent::setVisibility($path, $visibility); // TODO: Change the autogenerated stub
    }

    public function createDir($dirname, Config $config)
    {
        return parent::createDir($dirname, $config); // TODO: Change the autogenerated stub
    }

    public function deleteDir($dirname)
    {
        return parent::deleteDir($dirname); // TODO: Change the autogenerated stub
    }

    protected function deleteFileInfoObject(SplFileInfo $file)
    {
        parent::deleteFileInfoObject($file); // TODO: Change the autogenerated stub
    }

    protected function normalizeFileInfo(SplFileInfo $file)
    {
        return parent::normalizeFileInfo($file); // TODO: Change the autogenerated stub
    }

    protected function getFilePath(SplFileInfo $file)
    {
        return parent::getFilePath($file); // TODO: Change the autogenerated stub
    }

    protected function getRecursiveDirectoryIterator($path, $mode = RecursiveIteratorIterator::SELF_FIRST)
    {
        return parent::getRecursiveDirectoryIterator($path, $mode); // TODO: Change the autogenerated stub
    }

    protected function getDirectoryIterator($path)
    {
        return parent::getDirectoryIterator($path); // TODO: Change the autogenerated stub
    }

    protected function mapFileInfo(SplFileInfo $file)
    {
        return parent::mapFileInfo($file); // TODO: Change the autogenerated stub
    }

    protected function guardAgainstUnreadableFileInfo(SplFileInfo $file)
    {
        parent::guardAgainstUnreadableFileInfo($file); // TODO: Change the autogenerated stub
    }


    /**
     * @param $destPath
     * @return string
     */
    protected function attachEncryptionMarkers($destPath)
    {
        return $destPath . self::FILENAME_POSTFIX;
    }

    /**
     * @param $sourceRealPath
     * @return string|string[]|null
     */
    protected function detachEncryptionMarkers($sourceRealPath)
    {
        return preg_replace('/(' . self::FILENAME_POSTFIX . ')$/', '', $sourceRealPath);
    }
}